name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: |
          build/_deps/icu-src
          build/_deps/icu-build
          build/_deps/icu-subbuild
        key: ${{ hashFiles('cmake/icu.cmake') }}
    - name: test
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --parallel --target mcfile-example --config Release --verbose
        cmake --build . --parallel --target mcfile-test --config Release --verbose
        ./mcfile-test
